-- AlterTable
ALTER TABLE "discount_campaigns" ADD COLUMN     "brands" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "buyQty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "daysOfWeek" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "discountOnNth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "icon" TEXT NOT NULL DEFAULT '🏷️',
ADD COLUMN     "maxPerPurchase" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minQty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "payQty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scope" TEXT NOT NULL DEFAULT 'all';
